name: Java CI with Maven

on:
  push:
  workflow_dispatch:  # button shown only when in default branch

jobs:
  build:

    runs-on: docker-node-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        path: target/
