############################################################################################
# documentation:
# - https://docs.gitea.com/usage/actions/overview
# - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
# - https://docs.gitea.com/usage/actions/faq#what-workflow-trigger-events-does-gitea-support
############################################################################################
# Mirror this repo to a second mirror, e.g. Github
# - create repo if needed
# - sync otherwise
############################################################################################

name: "Mirror repo to ${{ vars.SCND_MIRROR_ORG_NAME }}"
run-name: Initiated by ${{ gitea.actor }}
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  workflow_dispatch:  # button shown only when in default branch
  workflow_call:      # allow to call it

jobs:
  build:
    runs-on: docker-node-latest

    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.LOCAL_TOKEN_RO }}

    - name: "Setup Github CLI"
      env:
        GH_TOKEN: ${{ secrets.SCND_MIRROR_TOKEN_RW }}
      run: |
        # install github cli:
        (type -p wget >/dev/null || (apt update >/dev/null && apt-get install wget -y >/dev/null)) \
            && mkdir -p -m 755 /etc/apt/keyrings \
                && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
                && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && apt update >/dev/null \
            && apt install gh -y >/dev/null
        # login to Github:
        gh auth login || (gh auth status 2>&1 | grep 'Logged in')

    - name: "Create/Sync repos with configured mirror"
      # https://github.com/k8scat/action-mirror-git
      uses: k8scat/action-mirror-git@v0.1.3
      with:
        source_protocol: https
        source_host: ${{ vars.LOCAL_ORG_DOMAIN }}
        source_port: ${{ vars.LOCAL_ORG_PORT }}
        source_username: "${{ vars.LOCAL_ORG_NAME }}"
        source_token: ${{ secrets.LOCAL_TOKEN_RO }}
        dest_protocol: https
        dest_host: ${{ vars.SCND_MIRROR_ORG_DOMAIN }}
        dest_username: "${{ vars.SCND_MIRROR_ORG_NAME }}"
        dest_token: ${{ secrets.SCND_MIRROR_TOKEN_RW }}
        mirror_repos: ${{ github.event.repository.name }}
        # creation is handled by
        # https://code.binbash.rocks/AXP.OS/actions/.gitea/workflows/activate_mirror.yaml
        #dest_create_repo_script: |
        #  gh repo create ${{ vars.SCND_MIRROR_ORG_NAME }}/${{ github.event.repository.name }} \
        #    --public --source=. --disable-issues --disable-wiki --team bots \
        #    --description "Mirror of: https://${{vars.LOCAL_ORG_DOMAIN}}/${{vars.LOCAL_ORG_NAME}}/${{ github.event.repository.name }} (requires a login)"
        #  gh api -X PUT "/orgs/${{ vars.SCND_MIRROR_ORG_NAME }}/teams/bots/repos/${{ vars.SCND_MIRROR_ORG_NAME }}/${{ github.event.repository.name }}" -f 'permission=maintain'

    - name: "Set default branch"
      env:
        GH_TOKEN: ${{ secrets.SCND_MIRROR_TOKEN_RW }}
      run: |
        echo "repo: >${{ github.event.repository.name }}<"
        DEFBR=$(git branch --show-current)
        echo "current on: >$DEFBR<"
        gh repo edit ${{ vars.SCND_MIRROR_ORG_NAME }}/${{ github.event.repository.name }} --default-branch $DEFBR
        if [ "$?" == "0" ]; then
          echo "default branch set to: $DEFBR"
        else
          echo -e "WARNING: issue occured while setting default branch to $DEFBR: $?"
        fi

    - name: "Sync LFS"
      uses: valtech-sd/git-sync@v9
      with:
        source_repo: "https://tok:${{ secrets.LOCAL_TOKEN_RO }}@${{ vars.LOCAL_ORG_DOMAIN }}:${{ vars.LOCAL_ORG_PORT }}/${{ vars.LOCAL_ORG_NAME }}/${{ github.event.repository.name }}"
        source_branch: "${{ github.event.ref }}"
        destination_repo: "https://tok:${{ secrets.SCND_MIRROR_TOKEN_RW }}@${{ vars.SCND_MIRROR_ORG_DOMAIN }}/${{ vars.SCND_MIRROR_ORG_NAME }}/${{ github.event.repository.name }}"
        destination_branch: "${{ github.event.ref }}"